# chosen based on my judgement
constant_length_descriptors = [
    "short",
    "brief",
    "concise",
    "medium-length",
    "average-length",
    "moderate-length",
    "long",
    "extensive",
    "verbose",
]

# calculated based on 25th, 50th and 75th percentiles of control group distributions
template_specific_title_descriptors = {
    "email": [
        "1000 characters long",
        "170 words long",
        "200 tokens long",
        "1100 characters long",
        "190 words long",
        "220 tokens long",
        "1300 characters long",
        "220 words long",
        "260 tokens long",
    ],
    "social": [
        "600 characters long",
        "100 words long",
        "130 tokens long",
        "700 characters long",
        "110 words long",
        "150 tokens long",
        "800 characters long",
        "120 words long",
        "170 tokens long",
    ],
    "cover": [
        "1300 characters long",
        "210 words long",
        "240 tokens long",
        "1400 characters long",
        "230 words long",
        "260 tokens long",
        "1500 characters long",
        "240 words long",
        "280 tokens long",
    ],
    "explanation": [
        "1100 characters long",
        "190 words long",
        "220 tokens long",
        "1300 characters long",
        "220 words long",
        "260 tokens long",
        "1500 characters long",
        "240 words long",
        "300 tokens long",
    ],
    "essay": [
        "2300 characters long",
        "350 words long",
        "400 tokens long",
        "2500 characters long",
        "370 words long",
        "430 tokens long",
        "2700 characters long",
        "400 words long",
        "470 tokens long",
    ],
}
